backend:
  name: github
  repo: wslyvh/cms
  branch: temp-cms

publish_mode: editorial_workflow
media_folder: static/assets/images/uploads
public_folder: /assets/images/uploads

collections:
  - name: pages
    label: Pages
    label_singular: Page
    folder: content/pages
    create: true
    nested:
      depth: 3
    fields:
      - { name: title, label: Title, widget: string }
      - { name: label, label: Label, widget: string }
      - { name: description, label: Description, widget: text }
      - { name: body, label: Body, widget: markdown }
      - { name: keywords, label: Keywords, widget: list }
      - { name: visible, label: Visible, widget: boolean, default: false }