backend:
  name: github
  repo: wslyvh/cms
  branch: main

publish_mode: editorial_workflow
media_folder: static/assets/uploads/images
public_folder: /assets/uploads/images

i18n:
  structure: multiple_folders
  locales: [en, es]
  default_locale: en

collections:
  - name: 'pages'
    label: 'Pages'
    label_singular: 'Page'
    folder: 'src/content/pages'
    create: true
    i18n: true
    nested:
      depth: 3 
    fields:
      - { name: 'title', label: 'Title', widget: 'string', i18n: true }
      - { name: 'body', label: 'Body', widget: 'markdown', i18n: true }
      - { name: 'order', label: 'Order', widget: 'number', i18n: 'duplicate', required: false, value_type: 'int', min: 1, max: 1000, step: 1 }
    meta: { path: { name: 'path', label: 'Path', widget: 'string', i18n: false, index_file: 'index', hint: 'Path can be a sub-folder (e.g. tickets/builder)' } }
